/* Automatically generated by version.sh, do not manually edit! */
#ifndef AVUTIL_FFVERSION_H
#define AVUTIL_FFVERSION_H
#define FFMPEG_VERSION "N-118724-g73f4668ef8-20250310"
#endif /* AVUTIL_FFVERSION_H */
